# https://taplo.tamasfe.dev/configuration/formatter-options.html#formatter-options

[formatting]
allowed_blank_lines = 1
reorder_arrays = true
reorder_inline_tables = true
reorder_keys = true

[[rule]]
include = ["**/Makefile.toml"]
keys = ["tasks.*"]

[rule.formatting]
reorder_arrays = false
