# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

[toolchain]
channel = "1.81"
components = [
  "cargo",
  "clippy",
  "llvm-tools",
  "rust-analyzer",
  "rust-docs",
  "rust-src",
  "rust-std",
  "rustc",
  "rustfmt",
]
profile = "default"
targets = []
